CREATE TABLE PUBLIC.USER
(
    id INT PRIMARY KEY NOT NULL IDENTITY,
    nickname VARCHAR(35) NOT NULL,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(70) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX "usr_id_uindex" ON PUBLIC.USER (id);
CREATE UNIQUE INDEX "usr_nickname_uindex" ON PUBLIC.USER (nickname);
CREATE UNIQUE INDEX "usr_email_uindex" ON PUBLIC.USER (email);

CREATE TABLE PUBLIC.PROJECT
(
  id INT PRIMARY KEY NOT NULL IDENTITY,
  name VARCHAR(35) NOT NULL,
  description VARCHAR(255),
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  creator_id INT NOT NULL
);
CREATE UNIQUE INDEX "prjct_id_uindex" ON PUBLIC.PROJECT (id);
CREATE UNIQUE INDEX "prjct_name_uindex" ON PUBLIC.PROJECT (name);

CREATE TABLE PUBLIC.TASK
(
  id INT PRIMARY KEY NOT NULL IDENTITY,
  name VARCHAR(35) NOT NULL,
  description VARCHAR(255),
  creation_date DATE NOT NULL,
  modification_date DATE DEFAULT CURRENT_DATE NOT NULL,
  project_id INT NOT NULL,
  status VARCHAR(50) NOT NULL,
  creator_id INT NOT NULL,
  assignee_id INT NOT NULL
);
CREATE UNIQUE INDEX "tsk_id_uindex" ON PUBLIC.TASK (id);
CREATE UNIQUE INDEX "tsk_name_uindex" ON PUBLIC.TASK (name);

ALTER TABLE PUBLIC.TASK
ADD CONSTRAINT TSK_PRJCT_ID_fk
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PUBLIC.TASK
ADD CONSTRAINT TSK_USR_ID_fk
FOREIGN KEY (CREATOR_ID) REFERENCES USER (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PUBLIC.TASK
ADD CONSTRAINT TSK_USR_ASSIGNEE_ID_fk
FOREIGN KEY (ASSIGNEE_ID) REFERENCES USER (ID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE PUBLIC.SUB_TASK
(
  id INT PRIMARY KEY NOT NULL IDENTITY,
  name VARCHAR(35) NOT NULL,
  description VARCHAR(255),
  creation_date DATE NOT NULL,
  modification_date TIMESTAMP DEFAULT current_timestamp,
  task_id INT NOT NULL,
  status VARCHAR(35) NOT NULL
);
CREATE UNIQUE INDEX "sbtsk_id_uindex" ON PUBLIC.SUB_TASK (id);
CREATE UNIQUE INDEX "sbtsk_name_uindex" ON PUBLIC.SUB_TASK (name);

ALTER TABLE PUBLIC.SUB_TASK
ADD CONSTRAINT SBTSK_TSK_ID_fk
FOREIGN KEY (TASK_ID) REFERENCES TASK (ID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE PUBLIC.project_user
(
  project_id INT NOT NULL,
  user_id INT NOT NULL
);
ALTER TABLE PUBLIC.project_user ADD CONSTRAINT P_U_PROJECT_ID_USER_ID_pk PRIMARY KEY (PROJECT_ID, USER_ID);
ALTER TABLE PUBLIC.project_user
ADD CONSTRAINT P_U_PRJCT_ID_fk
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PUBLIC.project_user
ADD CONSTRAINT P_U_USR_ID_fk
FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE ON UPDATE CASCADE;